### ISSUE TITLE
error when running Terraform Apply "The given key does not identify an element in this collection value"

### ISSUE THREAD

**Issue by willbranney73** [IBM/cp4d-deployment#84]
Error: Invalid index

  on vpc/vpc.tf line 19, in resource "ibm_is_vpc_address_prefix" "this":
  19:   zone = local.zones[count.index]
    |----------------
    | count.index is 1
    | local.zones is list of string with 1 element

The given key does not identify an element in this collection value.

Error: Invalid index

  on vpc/vpc.tf line 19, in resource "ibm_is_vpc_address_prefix" "this":
  19:   zone = local.zones[count.index]
    |----------------
    | count.index is 2
    | local.zones is list of string with 1 element

The given key does not identify an element in this collection value.

**Comment by praveshcompiles** [comment]
Hi,
I'm not sure what configuration you are deploying. I'll specify all the use cases here - 
Please make sure the value of the variable - "no_of_zones" should be 1 for single zone deployment otherwise it should be consistent with no. of zones you need for multizone. 
Make sure multizone variable is set to true or false. 
In case of exisiting VPC deployment, "no_of_zones" should be consistent with number of vpc subnets.

**Comment by willbranney73** [comment]
OK Thank you. I think I had inconsistent values. multizone =false but now working with no of zones set 1
