### ISSUE TITLE
node configuration

### ISSUE THREAD

**Issue by willbranney73** [IBM/cp4d-deployment#89]
I created a single zone 6 node cluster but it created 6 worker/master nodes. Is it possible to use this script to create  a 6 node cluster with 3 master/worker and 3 worker nodes? what settings are required in terraform.tfvars?

**Comment by maulikshah999** [comment]
@willbranney73 Which cloud provider are you using AWS/Azure/IBM Cloud? Is it `self-managed` or `managed openshift`?

**Comment by willbranney73** [comment]
I am using Managed-openshift for IBM Cloud.

**Comment by praveshcompiles** [comment]
Hi @willbranney73 
As far as I am aware, we don't have control over which nodes to make master/worker as the ROKS cluster is installed via Ibmcloud terraform api. I will still take a look in the APIs if there is a way to achieve this.

**Comment by shankarpentyala07** [comment]
Hi @willbranney73 ,
Apologies for the delayed response.

All the nodes listed are worker nodes.

The reason why do my worker nodes have the master role?
When you run oc get nodes or oc describe node , you might see that the worker nodes have master,worker roles. In OpenShift Container Platform clusters, operators use the master role as a nodeSelector so that OCP can deploy default components that are controlled by operators, such as the internal registry, in your cluster. No master node processes, such as the API server or Kubernetes scheduler, run on your worker nodes. For more information about master and worker node components, see Red Hat OpenShift architecture.

For ,Red Hat OpenShift on IBM Cloud - IBM sets up the master, manages the control plane components, and automatically applies master patch updates for you. The masters are highly available and backed up automatically.

Please refer the deployment architecture where the control plane(master) is IBM Managed:
https://github.com/IBM/cp4d-deployment/blob/master/managed-openshift/ibmcloud/README.md#deployment-topology


Additional docs for the same info:
https://cloud.ibm.com/docs/openshift?topic=openshift-planning_worker_nodes (why do my worker nodes have master label)
https://cloud.ibm.com/docs/openshift?topic=openshift-cs_ov (Master nodes are IBM Managed in ROKS.

Please let me know if you have more queries
